name: JaxCQL
# channels:
#     - https://conda.anaconda.org/conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - mpi4py
    - patchelf
    - pip:
        - -f https://storage.googleapis.com/jax-releases/jax_releases.html
        # - -f https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.1.76+cuda11.cudnn82-cp37-none-manylinux2010_x86_64.whl
        - jax[cuda]==0.2.26
        - flax
        - optax
        - distrax
        - Cython
        - scikit-image
        - tqdm
        - seaborn
        - gym==0.21.0
        - mujoco_py==2.0.2.5
        - box2d
        - absl-py
        - opencv-python
        - pygame
        - gtimer
        - joblib
        - git+https://github.com/young-geng/d4rl@master#egg=d4rl
        - wandb
        - ml_collections
